-- MySQL Script generated by MySQL Workbench
-- 05/19/15 17:35:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DbMysql06
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DbMysql06
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DbMysql06` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `DbMysql06` ;

-- -----------------------------------------------------
-- Table `DbMysql06`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DbMysql06`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `wasBornOnDate` DATE NULL,
  `wasBornInLocation` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `fk_user_location1_idx` (`wasBornInLocation` ASC),
  CONSTRAINT `fk_user_location1`
    FOREIGN KEY (`wasBornInLocation`)
    REFERENCES `DbMysql06`.`location` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `DbMysql06`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DbMysql06`.`location` (
  `name` VARCHAR(45) NOT NULL,
  `latitude` FLOAT NOT NULL,
  `longtitude` FLOAT NOT NULL,
  `wikiURL` VARCHAR(100) NULL,
  `ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbMysql06`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DbMysql06`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `wasBornOnDate` DATE NULL,
  `wasBornInLocation` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `fk_user_location1_idx` (`wasBornInLocation` ASC),
  CONSTRAINT `fk_user_location1`
    FOREIGN KEY (`wasBornInLocation`)
    REFERENCES `DbMysql06`.`location` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `DbMysql06`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DbMysql06`.`person` (
  `ID` VARCHAR(100) NOT NULL,
  `wikiURL` VARCHAR(100) NULL,
  `diedOnDate` DATE NULL,
  `wasBornOnDate` DATE NOT NULL,
  `addedByUser` VARCHAR(16) NOT NULL,
  `wasBornInLocation` VARCHAR(100) NOT NULL,
  `diedInLocation` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_person_user1_idx` (`addedByUser` ASC),
  INDEX `fk_person_location1_idx` (`wasBornInLocation` ASC),
  INDEX `fk_person_location2_idx` (`diedInLocation` ASC),
  CONSTRAINT `fk_person_user1`
    FOREIGN KEY (`addedByUser`)
    REFERENCES `DbMysql06`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_location1`
    FOREIGN KEY (`wasBornInLocation`)
    REFERENCES `DbMysql06`.`location` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_location2`
    FOREIGN KEY (`diedInLocation`)
    REFERENCES `DbMysql06`.`location` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbMysql06`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DbMysql06`.`category` (
  `categoryID` INT NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`categoryID`));


-- -----------------------------------------------------
-- Table `DbMysql06`.`user_has_favorite_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DbMysql06`.`user_has_favorite_person` (
  `user_username` VARCHAR(16) NOT NULL,
  `person_ID` VARCHAR(32) NOT NULL,
  INDEX `fk_user_has_person_person1_idx` (`person_ID` ASC),
  INDEX `fk_user_has_person_user_idx` (`user_username` ASC),
  PRIMARY KEY (`user_username`, `person_ID`),
  CONSTRAINT `fk_user_has_person_user`
    FOREIGN KEY (`user_username`)
    REFERENCES `DbMysql06`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_person_person1`
    FOREIGN KEY (`person_ID`)
    REFERENCES `DbMysql06`.`person` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `DbMysql06`.`person_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DbMysql06`.`person_has_category` (
  `personID` VARCHAR(32) NOT NULL,
  `categoryID` INT NOT NULL,
  PRIMARY KEY (`personID`, `categoryID`),
  INDEX `fk_person_has_category_category1_idx` (`categoryID` ASC),
  INDEX `fk_person_has_category_person1_idx` (`personID` ASC),
  CONSTRAINT `fk_person_has_category_person1`
    FOREIGN KEY (`personID`)
    REFERENCES `DbMysql06`.`person` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_has_category_category1`
    FOREIGN KEY (`categoryID`)
    REFERENCES `DbMysql06`.`category` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
